name: ' CI/CD'

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/*
      - feature/*
    paths-ignore:
      - '**.md'
      - '.github/*.json'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/*.json'

permissions:
  contents: read
  actions: read
  pull-requests: write

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    runs-on: windows-latest
    outputs:
      projects: ${{ steps.determineProjectsToBuild.outputs.ProjectsJson }}
      projectsCount: ${{ steps.determineProjectsToBuild.outputs.ProjectsCount }}
      environments: ${{ steps.determineDeploymentEnvironments.outputs.EnvironmentsJson }}
      environmentsCount: ${{ steps.determineDeploymentEnvironments.outputs.EnvironmentsCount }}
      settings: ${{ steps.readSettings.outputs.SettingsJson }}
      buildModes: ${{ steps.readSettings.outputs.BuildModesJson }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v6.0
        with:
          shell: powershell

      - name: Read Settings
        id: readSettings
        uses: microsoft/AL-Go-Actions/ReadSettings@v6.0
        with:
          shell: powershell

      - name: Determine Projects To Build
        id: determineProjectsToBuild
        uses: microsoft/AL-Go-Actions/DetermineProjectsToBuild@v6.0
        with:
          shell: powershell

      - name: Determine Deployment Environments
        id: determineDeploymentEnvironments
        uses: microsoft/AL-Go-Actions/DetermineDeploymentEnvironments@v6.0
        with:
          shell: powershell
          getEnvironments: '*'
          type: 'CD'

  Build:
    needs: [ Initialization ]
    if: needs.Initialization.outputs.projectsCount > 0
    runs-on: ${{ fromJson(needs.Initialization.outputs.settings).githubRunner }}
    strategy:
      matrix:
        project: ${{ fromJson(needs.Initialization.outputs.projects) }}
        buildMode: ${{ fromJson(needs.Initialization.outputs.buildModes) }}
      fail-fast: false
    name: Build ${{ matrix.project }} (${{ matrix.buildMode }})
    outputs:
      AppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.AppsArtifactsName }}
      TestAppsArtifactsName: ${{ steps.calculateArtifactNames.outputs.TestAppsArtifactsName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v6.0
        with:
          shell: powershell
          project: ${{ matrix.project }}

      - name: Read Secrets
        id: readSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v6.0
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'licenseFileUrl,insiderSasToken,keyVaultCertificateUrl,keyVaultCertificatePassword,keyVaultClientId'

      - name: Run Pipeline
        id: runPipeline
        uses: microsoft/AL-Go-Actions/RunPipeline@v6.0
        with:
          shell: powershell
          project: ${{ matrix.project }}
          buildMode: ${{ matrix.buildMode }}
          secrets: '${{ steps.readSecrets.outputs.Secrets }}'

      - name: Calculate Artifact Names
        id: calculateArtifactNames
        uses: microsoft/AL-Go-Actions/CalculateArtifactNames@v6.0
        if: success() || failure()
        with:
          shell: powershell
          project: ${{ matrix.project }}
          buildMode: ${{ matrix.buildMode }}

      - name: Publish Apps Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ steps.calculateArtifactNames.outputs.AppsArtifactsName }}
          path: '${{ matrix.project }}/.buildartifacts/Apps/'
          if-no-files-found: ignore
          retention-days: 30

      - name: Publish Test Apps Artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ steps.calculateArtifactNames.outputs.TestAppsArtifactsName }}
          path: '${{ matrix.project }}/.buildartifacts/TestApps/'
          if-no-files-found: ignore
          retention-days: 30

      - name: Cleanup
        if: always()
        uses: microsoft/AL-Go-Actions/PipelineCleanup@v6.0
        with:
          shell: powershell
          project: ${{ matrix.project }}

  PostProcess:
    runs-on: windows-latest
    needs: [ Initialization, Build ]
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v6.0
        with:
          shell: powershell
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
