name: 'Create Release'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: 'App version to release (Major.Minor)'
        required: true
        default: ''
      name:
        description: 'Name of release (default is the app version)'
        required: false
        default: ''
      tag:
        description: 'Tag for release (default is version)'
        required: false
        default: ''
      draft:
        description: 'Create as draft release'
        type: boolean
        default: true
      prerelease:
        description: 'Create as pre-release'
        type: boolean
        default: false

permissions:
  contents: write
  pull-requests: write
  actions: read

defaults:
  run:
    shell: powershell

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  CreateRelease:
    runs-on: windows-latest
    outputs:
      artifacts: ${{ steps.createRelease.outputs.Artifacts }}
      releaseId: ${{ steps.createRelease.outputs.ReleaseId }}
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize the workflow
        id: init
        uses: microsoft/AL-Go-Actions/WorkflowInitialize@v6.0
        with:
          shell: powershell

      - name: Read Settings
        uses: microsoft/AL-Go-Actions/ReadSettings@v6.0
        with:
          shell: powershell

      - name: Read Secrets
        id: readSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v6.0
        with:
          shell: powershell
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'

      - name: Determine Projects
        id: determineProjects
        uses: microsoft/AL-Go-Actions/DetermineProjectsToBuild@v6.0
        with:
          shell: powershell

      - name: Create Release
        id: createRelease
        uses: microsoft/AL-Go-Actions/CreateRelease@v6.0
        with:
          shell: powershell
          token: ${{ steps.readSecrets.outputs.ghTokenWorkflow || github.token }}
          parentTelemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          projects: ${{ steps.determineProjects.outputs.ProjectsJson }}
          appVersion: ${{ github.event.inputs.appVersion }}
          name: ${{ github.event.inputs.name }}
          tag: ${{ github.event.inputs.tag }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}

  PostProcess:
    runs-on: windows-latest
    needs: CreateRelease
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Finalize the workflow
        id: PostProcess
        uses: microsoft/AL-Go-Actions/WorkflowPostProcess@v6.0
        with:
          shell: powershell
          telemetryScopeJson: ${{ needs.CreateRelease.outputs.telemetryScopeJson }}
